spring:
  profiles:
    active: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
logging:
  level:
    com.psymoney.authserver: DEBUG
    org.springframework: ERROR
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
spring:
  profiles:
    active: "test"
